import type { Product } from "@/types";

/**
 * Temporary local data so the Home/Shop UI has something real to render.
 * Swap these out once the Product API milestone lands — every component
 * that consumes this only needs a Product[]/string[] shape, so the switch
 * to `fetch("/api/products")` is a one-line change, not a rewrite.
 */
export const CATEGORIES = [
  { name: "Electronics", slug: "electronics", image: "https://picsum.photos/seed/kemer-electronics/600/600" },
  { name: "Home & Living", slug: "home-living", image: "https://picsum.photos/seed/kemer-home/600/600" },
  { name: "Fashion", slug: "fashion", image: "https://picsum.photos/seed/kemer-fashion/600/600" },
  { name: "Beauty", slug: "beauty", image: "https://picsum.photos/seed/kemer-beauty/600/600" },
];

function product(
  id: string,
  overrides: Omit<Product, "_id" | "createdAt" | "updatedAt">
): Product {
  return {
    _id: id,
    createdAt: `2026-01-${String(1 + (Number(id) % 28)).padStart(2, "0")}T00:00:00.000Z`,
    updatedAt: `2026-01-${String(1 + (Number(id) % 28)).padStart(2, "0")}T00:00:00.000Z`,
    ...overrides,
  };
}

export const ALL_PRODUCTS: Product[] = [
  product("1", {
    name: "Wireless Charging Stand",
    slug: "wireless-charging-stand",
    description: "A fast-charging stand with a soft-touch matte finish, angled for hands-free calls.",
    category: "Electronics",
    price: 1450,
    images: ["https://picsum.photos/seed/kemer-p1/800/1000"],
    colors: ["Black", "White"],
    sizes: [],
    featured: true,
    inStock: true,
  }),
  product("2", {
    name: "Ceramic Pour-Over Set",
    slug: "ceramic-pour-over-set",
    description: "Hand-finished ceramic dripper and carafe for a slower, better morning.",
    category: "Home & Living",
    price: 2200,
    images: ["https://picsum.photos/seed/kemer-p2/800/1000"],
    colors: ["Sand"],
    sizes: [],
    featured: true,
    inStock: true,
  }),
  product("3", {
    name: "Everyday Canvas Tote",
    slug: "everyday-canvas-tote",
    description: "Heavyweight canvas tote with leather straps, built to carry a full day.",
    category: "Fashion",
    price: 980,
    images: ["https://picsum.photos/seed/kemer-p3/800/1000"],
    colors: ["Olive", "Black", "Natural"],
    sizes: ["One Size"],
    featured: true,
    inStock: true,
  }),
  product("4", {
    name: "Shea & Aloe Body Balm",
    slug: "shea-aloe-body-balm",
    description: "Whipped shea butter with cold-pressed aloe, unscented and fast-absorbing.",
    category: "Beauty",
    price: 620,
    images: ["https://picsum.photos/seed/kemer-p4/800/1000"],
    colors: [],
    sizes: ["150ml"],
    featured: true,
    inStock: false,
  }),
  product("5", {
    name: "Compact Bluetooth Speaker",
    slug: "compact-bluetooth-speaker",
    description: "Pocket-sized speaker with a surprisingly full sound and 12-hour battery.",
    category: "Electronics",
    price: 1890,
    images: ["https://picsum.photos/seed/kemer-p5/800/1000"],
    colors: ["Charcoal", "Sky Blue"],
    sizes: [],
    featured: false,
    inStock: true,
  }),
  product("6", {
    name: "USB-C Fast Charger, 30W",
    slug: "usb-c-fast-charger-30w",
    description: "Compact GaN charger that fits a travel pouch without adding bulk.",
    category: "Electronics",
    price: 890,
    images: ["https://picsum.photos/seed/kemer-p6/800/1000"],
    colors: ["White"],
    sizes: [],
    featured: false,
    inStock: true,
  }),
  product("7", {
    name: "Over-Ear Noise Isolating Headphones",
    slug: "over-ear-headphones",
    description: "Padded over-ear headphones built for long commutes and longer playlists.",
    category: "Electronics",
    price: 3200,
    images: ["https://picsum.photos/seed/kemer-p7/800/1000"],
    colors: ["Black"],
    sizes: [],
    featured: false,
    inStock: false,
  }),
  product("8", {
    name: "Linen Table Runner",
    slug: "linen-table-runner",
    description: "Stonewashed linen runner that softens with every wash.",
    category: "Home & Living",
    price: 750,
    images: ["https://picsum.photos/seed/kemer-p8/800/1000"],
    colors: ["Natural", "Charcoal"],
    sizes: [],
    featured: false,
    inStock: true,
  }),
  product("9", {
    name: "Hand-Blown Glass Vase",
    slug: "hand-blown-glass-vase",
    description: "Each piece is slightly different — that's the point.",
    category: "Home & Living",
    price: 1600,
    images: ["https://picsum.photos/seed/kemer-p9/800/1000"],
    colors: ["Clear", "Amber"],
    sizes: [],
    featured: false,
    inStock: true,
  }),
  product("10", {
    name: "Woven Storage Basket",
    slug: "woven-storage-basket",
    description: "Hand-woven basket sized for blankets, toys, or a tidy entryway.",
    category: "Home & Living",
    price: 1100,
    images: ["https://picsum.photos/seed/kemer-p10/800/1000"],
    colors: ["Natural"],
    sizes: ["Small", "Large"],
    featured: false,
    inStock: true,
  }),
  product("11", {
    name: "Relaxed Linen Shirt",
    slug: "relaxed-linen-shirt",
    description: "Breathable linen shirt cut for warm days and long lunches.",
    category: "Fashion",
    price: 1350,
    images: ["https://picsum.photos/seed/kemer-p11/800/1000"],
    colors: ["White", "Sand", "Olive"],
    sizes: ["S", "M", "L", "XL"],
    featured: false,
    inStock: true,
  }),
  product("12", {
    name: "Leather Ankle Boots",
    slug: "leather-ankle-boots",
    description: "Full-grain leather boots, resoleable and built to age well.",
    category: "Fashion",
    price: 4200,
    images: ["https://picsum.photos/seed/kemer-p12/800/1000"],
    colors: ["Brown", "Black"],
    sizes: ["39", "40", "41", "42", "43"],
    featured: false,
    inStock: true,
  }),
  product("13", {
    name: "Minimal Leather Belt",
    slug: "minimal-leather-belt",
    description: "A single stitch line, a brushed buckle, nothing else.",
    category: "Fashion",
    price: 850,
    images: ["https://picsum.photos/seed/kemer-p13/800/1000"],
    colors: ["Black", "Tan"],
    sizes: ["S/M", "L/XL"],
    featured: false,
    inStock: false,
  }),
  product("14", {
    name: "Rosehip Facial Oil",
    slug: "rosehip-facial-oil",
    description: "Cold-pressed rosehip oil for evening skincare routines.",
    category: "Beauty",
    price: 780,
    images: ["https://picsum.photos/seed/kemer-p14/800/1000"],
    colors: [],
    sizes: ["30ml"],
    featured: false,
    inStock: true,
  }),
  product("15", {
    name: "Charcoal Clay Mask",
    slug: "charcoal-clay-mask",
    description: "Deep-cleansing clay mask, gentle enough for weekly use.",
    category: "Beauty",
    price: 540,
    images: ["https://picsum.photos/seed/kemer-p15/800/1000"],
    colors: [],
    sizes: ["100ml"],
    featured: false,
    inStock: true,
  }),
  product("16", {
    name: "Sandalwood Solid Perfume",
    slug: "sandalwood-solid-perfume",
    description: "A warm, low-key scent in a pocket-sized tin.",
    category: "Beauty",
    price: 690,
    images: ["https://picsum.photos/seed/kemer-p16/800/1000"],
    colors: [],
    sizes: ["15g"],
    featured: false,
    inStock: true,
  }),
];

export const FEATURED_PRODUCTS: Product[] = ALL_PRODUCTS.filter((p) => p.featured);
